apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node.serviceAccountName" . }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
  annotations:
  {{- if or .Values.dataSnapshot.restoreData .Values.dataSnapshot.backupData}}
    eks.amazonaws.com/role-arn: {{.Values.dataSnapshot.awsSnapshotIamRoleArn}}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
