apiVersion: v1
kind: Service
metadata:
  name: {{ include "rpc-proxy.fullname" . }}
  labels:
    {{- include "rpc-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "rpc-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: proxyd-http
      targetPort: proxyd-http
      port: 8545
      protocol: TCP
    - name: proxyd-ws
      targetPort: proxyd-ws
      port: 8546
      protocol: TCP
    - name: proxyd-metrics
      targetPort: proxyd-metrics
      port: 7300
      protocol: TCP
    - name: dugtrio-http
      targetPort: dugtrio-http
      port: 9545
      protocol: TCP
